/*!
* \file   TFEL/Material/MonoCristal_UO2IntegrationData.hxx
* \brief  this file implements the MonoCristal_UO2IntegrationData class.
*         File generated by tfel version 4.2.0-dev
* \author Luc Portelette / Thomas Helfer / Etienne Castelier
 */

#ifndef LIB_TFELMATERIAL_MONOCRISTAL_UO2_INTEGRATION_DATA_HXX
#define LIB_TFELMATERIAL_MONOCRISTAL_UO2_INTEGRATION_DATA_HXX

#include<string>
#include<iostream>
#include<limits>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsScalar.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/TypeTraits/Promote.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Math/tvector.hxx"
#include"TFEL/Math/Vector/tvectorIO.hxx"
#include"TFEL/Math/stensor.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include"TFEL/Math/tensor.hxx"
#include"TFEL/Math/t2tot2.hxx"
#include"TFEL/Math/t2tost2.hxx"
#include"TFEL/Math/st2tot2.hxx"
#include"TFEL/Math/General/CubicRoots.hxx"
#include "TFEL/Material/MonoCristal_UO2SlipSystems.hxx"

#include"MFront/Castem/Castem.hxx"

namespace tfel::material{

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType, bool use_qt>
class MonoCristal_UO2IntegrationData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
 operator <<(std::ostream&,const MonoCristal_UO2IntegrationData<hypothesis, NumericType, false>&);

//! \brief forward declaration
template<typename NumericType>
std::ostream&
 operator <<(std::ostream&,const MonoCristal_UO2IntegrationData<ModellingHypothesis::TRIDIMENSIONAL, NumericType, false>&);

template<typename NumericType>
class MonoCristal_UO2IntegrationData<ModellingHypothesis::TRIDIMENSIONAL, NumericType, false>
{

static constexpr ModellingHypothesis::Hypothesis hypothesis = ModellingHypothesis::TRIDIMENSIONAL;
static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const MonoCristal_UO2IntegrationData&);

static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using numeric_type = typename Types::numeric_type;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using DeformationGradientRateTensor = typename Types::DeformationGradientRateTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = FiniteStrainBehaviourTangentOperator<N,stress>;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

protected: 

/*!
 * \brief F at the end of the time step
 */
DeformationGradientTensor F1;

/*!
 * \brief time increment
 */
time dt;

temperature dT;
public:

/*!
* \brief Default constructor
*/
MonoCristal_UO2IntegrationData()
{}

/*!
* \brief Copy constructor
*/
MonoCristal_UO2IntegrationData(const MonoCristal_UO2IntegrationData& src)
: F1(src.F1),
dt(src.dt),
dT(src.dT)
{}

/*
 * \brief constructor for the Castem interface
 * \param[in] CASTEMdt_: time increment
 * \param[in] CASTEMdT_: temperature increment
 * \param[in] CASTEMdext_vars: external state variables increments
 */
MonoCristal_UO2IntegrationData(const NumericType* const CASTEMdt_,
const NumericType* const CASTEMdT_,const NumericType* const)
: dt(*CASTEMdt_),dT(*CASTEMdT_)
{
}

void setCASTEMIntegrationDataGradients(const NumericType* const CASTEMdstran)
{
DeformationGradientTensor::buildFromFortranMatrix(this->F1,CASTEMdstran);
}


/*
* \brief scale the integration data by a scalar.
*/
template<typename Scal>
typename std::enable_if<
tfel::typetraits::IsFundamentalNumericType<Scal>::cond&&
tfel::typetraits::IsScalar<Scal>::cond&&
tfel::typetraits::IsReal<Scal>::cond&&
std::is_same<NumericType,typename tfel::typetraits::Promote<NumericType,Scal>::type>::value,
MonoCristal_UO2IntegrationData&
>::type
scale(const MonoCristal_UO2BehaviourData<hypothesis, NumericType, false>& behaviourData, const Scal time_scaling_factor){
this->dt   *= time_scaling_factor;
this->F1 = (1-time_scaling_factor)*(behaviourData.F0)+time_scaling_factor*(this->F1);
this->dT *= time_scaling_factor;
return *this;
}

/*!
* \brief update the driving variable in case of substepping.
*/
MonoCristal_UO2IntegrationData&
updateDrivingVariables(const MonoCristal_UO2BehaviourData<hypothesis, NumericType, false>& behaviourData){
this->F1 += this->F1 - (behaviourData.F0);
return *this;
}

}; // end of MonoCristal_UO2IntegrationDataclass

template<typename NumericType>
std::ostream&
operator <<(std::ostream& os,const MonoCristal_UO2IntegrationData<ModellingHypothesis::TRIDIMENSIONAL, NumericType, false>& b)
{
os << "F₁ : " << b.F1 << '\n';
os << "σ : " << b.sig << '\n';
os << "Δt : " << b.dt << '\n';
os << "ΔT : " << b.dT << '\n';
return os;
}

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_MONOCRISTAL_UO2_INTEGRATION_DATA_HXX */
