/*!
* \file   MonoCristal_UO2.cxx
* \brief  this file implements the MonoCristal_UO2 Behaviour.
*         File generated by tfel version 4.2.0-dev
* \author Luc Portelette / Thomas Helfer / Etienne Castelier
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/MonoCristal_UO2BehaviourData.hxx"
#include"TFEL/Material/MonoCristal_UO2IntegrationData.hxx"
#include"TFEL/Material/MonoCristal_UO2.hxx"

namespace tfel::material{

MonoCristal_UO2TridimensionalParametersInitializer&
MonoCristal_UO2TridimensionalParametersInitializer::get()
{
static MonoCristal_UO2TridimensionalParametersInitializer i;
return i;
}

MonoCristal_UO2TridimensionalParametersInitializer::MonoCristal_UO2TridimensionalParametersInitializer()
{
// Reading parameters from a file
MonoCristal_UO2TridimensionalParametersInitializer::readParameters(*this,"MonoCristal_UO2-parameters.txt");
MonoCristal_UO2TridimensionalParametersInitializer::readParameters(*this,"MonoCristal_UO2Tridimensional-parameters.txt");
}

void
MonoCristal_UO2TridimensionalParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("epsilon",key)==0){
MonoCristal_UO2ParametersInitializer::get().set("epsilon",v);
} else if(::strcmp("theta",key)==0){
MonoCristal_UO2ParametersInitializer::get().set("theta",v);
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
MonoCristal_UO2ParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
MonoCristal_UO2ParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
MonoCristal_UO2ParametersInitializer::get().set("numerical_jacobian_epsilon",v);
} else {
tfel::raise("MonoCristal_UO2TridimensionalParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
MonoCristal_UO2TridimensionalParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
MonoCristal_UO2ParametersInitializer::get().set("iterMax",v);
} else {
tfel::raise("MonoCristal_UO2TridimensionalParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

void
MonoCristal_UO2TridimensionalParametersInitializer::readParameters(MonoCristal_UO2TridimensionalParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
auto line = std::string{};
while(std::getline(f,line)){
auto tokens = tokenize(line);
auto throw_if = [ln = ln, line, fn](const bool mfront_c,
const std::string& mfront_error_message){
tfel::raise_if(mfront_c,"MonoCristal_UO2TridimensionalParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+mfront_error_message+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("epsilon"==tokens[0]){
MonoCristal_UO2ParametersInitializer::get().set("epsilon",
MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("theta"==tokens[0]){
MonoCristal_UO2ParametersInitializer::get().set("theta",
MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("iterMax"==tokens[0]){
MonoCristal_UO2ParametersInitializer::get().set("iterMax",
MonoCristal_UO2ParametersInitializer::getUnsignedShort(tokens[0],tokens[1]));
} else if("minimal_time_step_scaling_factor"==tokens[0]){
MonoCristal_UO2ParametersInitializer::get().set("minimal_time_step_scaling_factor",
MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
MonoCristal_UO2ParametersInitializer::get().set("maximal_time_step_scaling_factor",
MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("numerical_jacobian_epsilon"==tokens[0]){
MonoCristal_UO2ParametersInitializer::get().set("numerical_jacobian_epsilon",
MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

MonoCristal_UO2ParametersInitializer&
MonoCristal_UO2ParametersInitializer::get()
{
static MonoCristal_UO2ParametersInitializer i;
return i;
}

MonoCristal_UO2ParametersInitializer::MonoCristal_UO2ParametersInitializer()
{
this->epsilon = 1e-12;
this->theta = 1;
this->iterMax = 100;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
this->numerical_jacobian_epsilon = 1e-13;
// Reading parameters from a file
MonoCristal_UO2ParametersInitializer::readParameters(*this,"MonoCristal_UO2-parameters.txt");
}

void
MonoCristal_UO2ParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("epsilon",key)==0){
this->epsilon = v;
} else if(::strcmp("theta",key)==0){
this->theta = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
this->numerical_jacobian_epsilon = v;
} else {
tfel::raise("MonoCristal_UO2ParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
MonoCristal_UO2ParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
this->iterMax = v;
} else {
tfel::raise("MonoCristal_UO2ParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

double
MonoCristal_UO2ParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"MonoCristal_UO2ParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

unsigned short
MonoCristal_UO2ParametersInitializer::getUnsignedShort(const std::string& n,
const std::string& v)
{
unsigned short value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"MonoCristal_UO2ParametersInitializer::getUnsignedShort: "
"can't convert '"+v+"' to unsigned short for parameter '"+ n+"'");
return value;
}

void
MonoCristal_UO2ParametersInitializer::readParameters(MonoCristal_UO2ParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
auto line = std::string{};
while(std::getline(f,line)){
auto tokens = tokenize(line);
auto throw_if = [ln = ln, line, fn](const bool mfront_c,
const std::string& mfront_error_message){
tfel::raise_if(mfront_c,"MonoCristal_UO2ParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+mfront_error_message+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("epsilon"==tokens[0]){
pi.epsilon = MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("theta"==tokens[0]){
pi.theta = MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("iterMax"==tokens[0]){
pi.iterMax = MonoCristal_UO2ParametersInitializer::getUnsignedShort(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("numerical_jacobian_epsilon"==tokens[0]){
pi.numerical_jacobian_epsilon = MonoCristal_UO2ParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

