name: Spack And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop      # Spack version (examples: develop, releases/v0.21)
          buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
          color: true       # Force color output (SPACK_COLOR=always)
          path: spack       # Where to clone Spack
      - name: Install MFEM MGIS
        run: |
          git clone https://github.com/rprat-pro/spack-repo-mfem-mgis.git
          spack repo add spack-repo-mfem-mgis
          spack install mfem-mgis
      - name: Configure OperaHpc Test Cases
        shell: spack-sh {0}
        run: |
          spack load mfem
          spack load mfem-mgis
          export MFEMMGIS_DIR=`spack location -i mfem-mgis`/share/mfem-mgis/cmake/
          cmake -B ${{github.workspace}}/release 
      - name: Build OperaHpc Test Cases
        run:  cmake --build ${{github.workspace}}/release --config Release
      - name: Run examples
        shell: spack-sh {0}
        run: |
          spack load mfem-mgis
          make -j
          ctest
     

          
          
          
